### ISSUE TITLE
Readme simple component wrong command

### ISSUE THREAD

**Issue by claudio147** [valantic/spartacus-blueprint#2]
Is there the wrong command in the readme for a simple component?

> ng generate ./blueprints/src/collection.json:simpleComponent src/app/[PROJECT_NAME]/your/path/MySimpleComponentName

When I try following command it works:
`ng generate @valantic/spartacus-blueprints:simpleComponent src/app/[PROJECT_NAME]/elements/MySimpleTest`

**Comment by janwidmer** [comment]
Fixed
